spring:
  application:
    name: ms-busqueda

  datasource:
    url: jdbc:mysql://mariadb:3306/busqueda_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8086

ms:
  auth:
    url: http://ms-registro:8082
  catalogo:
    url: http://ms-catalogo:8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30