spring.application.name=suscripciones

spring.datasource.url=jdbc:mysql://host.docker.internal:3306/suscripciones
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db.migration

server.port=8085

ms.usuario.url=http://localhost:8082