spring.application.name=ms-catalogo

server.port=8081

spring.datasource.url=jdbc:mariadb://host.docker.internal:3306/catalogo_db
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


