spring.datasource.url=jdbc:mysql://host.docker.internal:3306/busqueda_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=8086

ms.auth.url=http://localhost:8082