spring.application.name=ms-busqueda
server.port=8086

spring.datasource.url=jdbc:mysql://host.docker.internal:3306/busqueda_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

ms.auth.url=http://localhost:8082
ms.catalogo.url=http://localhost:8081