spring.application.name=ms-reproduccion-descargas
server.port=8083

spring.datasource.url=jdbc:mariadb://host.docker.internal:3306/durocplus_reproduccion_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

ms.auth.url=http://localhost:8082