spring.application.name=ms-suscripciones

server.port=8085

# BASE DE DATOS
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/suscripciones}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# FLYWAY
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# MICROSERVICIO DE USUARIOS
ms.usuario.url=${MS_USUARIO_URL:http://localhost:8082}

# SPRING SECURITY
spring.security.user.name=admin
spring.security.user.password=admin123

# EUREKA CLIENT
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# DATAFAKER
app.datafaker.enabled=false
